### ISSUE TITLE
🛣️Proposal / Roadmap: hctournaments 2.0! Season based routing, Database integration, Revamped UI, Admin Dashboard & much more...

### ISSUE THREAD

**Issue by SamirMishra27** [SamirMishra27/hctournaments#2]
# Preface
The hctournaments web application (https://hctournaments.vercel.app/) is planned to undergo a complete rewrite to improve its functionality and add more features, making it more intuitive, accessible, and easily manageable from the backend. The goal is for it to become the one-stop solution for browsing any information related to hand cricket tournaments.

# The Goal
The overall goal and vision of hctournaments 2.0 are to make, manage, and organize official Hand Cricket tournaments as easily as possible. The aim is to ensure that dealing with routine tournament activities does not feel _like a chore or burden._

### Other smaller goals:
- To revamp the user interface (front-end part) using the latest cutting-edge frameworks and libraries, aimed at delivering web application content to the user as smoothly and quickly as possible.
- To integrate a database in the backend so that data can be securely stored with mobility and backup.
- Ability to access the information and stats of previously hosted tournaments, not just the current one.
- Discord login integration using OAuth, so that users could access rich information and stats pertaining to their account in future updates. (Laying the foundation to tie tournament stats with individuals' accounts)
- An Admin dashboard and a simple roles system to easily onboard trusted tournament organizers who could edit and modify tournament information in the absence of web admins, without the risk of misuse by others.

# Checkbox
- [x] - Season-based routing in both frontend & backend
- [x] - Revamped UI, to adopt the latest UI & UX trends and enhance user experience
- [x] - Database Integration in the backend of the application
- [x] - Dark mode & Light mode option in the web application
- [x] - Data & History of previously hosted tournaments
- [x] - Admin dashboard to edit & modify tournaments easily
- [x] - Routes for admin-related actions
- [x] - Discord OAuth login integration to identify normal & admin users

# The Roadmap: detailed explanation of each major feature
# Sketch
![hctournaments_outline_2 0_Untitled-2023-08-28-0254](https://github.com/SamirMishra27/hctournaments/assets/68955143/6465f222-7d45-48f2-8ce4-f103394a4546)

# ETA of release:
The expected time to complete this project will be by the end of **October 31st**. Due to unavoidable circumstances, this could be delayed to a much later date.

# Hosting
The project will still be hosted on **[Vercel](https://vercel.com/)**, the current front-end hosting provider.

# Conclusion
The revamp will hopefully make it easier to manage tournaments in a fast-paced life, with enough room for further improvement in the future.

**Comment by SamirMishra27** [comment]
And with that, **[hctournaments](https://hctournaments.vercel.app/)** 2.0 is now successfully complete! 🎉
Closing the issue now, but improvements will continue to be made.
